# Generated by Django 5.1.3 on 2026-07-16 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('mileage', models.PositiveIntegerField(verbose_name='Пробег')),
                ('vin', models.CharField(max_length=17, verbose_name='VIN номер')),
                ('front_photo', models.ImageField(upload_to='inspections/front/', verbose_name='Фото спереди')),
                ('rear_photo', models.ImageField(upload_to='inspections/rear/', verbose_name='Фото сзади')),
                ('left_photo', models.ImageField(upload_to='inspections/left/', verbose_name='Фото слева')),
                ('right_photo', models.ImageField(upload_to='inspections/right/', verbose_name='Фото справа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Осмотр авто',
                'verbose_name_plural': 'Осмотры авто',
                'ordering': ['-created_at'],
            },
        ),
    ]
