# Generated by Django 5.1.3 on 2026-07-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_branch_vehicleinspection_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleinspection',
            name='title',
            field=models.CharField(blank=True, max_length=120, verbose_name='Название'),
        ),
    ]
