# Generated by Django 5.1.3 on 2026-07-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_alter_vehicleinspection_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleinspection',
            name='mileage_photo',
            field=models.ImageField(blank=True, null=True, upload_to='inspections/mileage/', verbose_name='Фото пробега'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='vin_photo',
            field=models.ImageField(blank=True, null=True, upload_to='inspections/vin/', verbose_name='Фото VIN'),
        ),
        migrations.AlterField(
            model_name='vehicleinspection',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Пробег'),
        ),
        migrations.AlterField(
            model_name='vehicleinspection',
            name='vin',
            field=models.CharField(blank=True, max_length=17, verbose_name='VIN номер'),
        ),
    ]
