# Generated by Django 5.1.3 on 2026-07-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0004_vehicleinspection_mileage_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='OpenAI', max_length=120, verbose_name='Название')),
                ('api_key', models.CharField(max_length=255, verbose_name='API key')),
                ('model', models.CharField(default='gpt-5.6', max_length=80, verbose_name='Модель')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'AI API key',
                'verbose_name_plural': 'AI API keys',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
    ]
