# Generated by Django 5.1.3 on 2026-07-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0005_aiapikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('operator', 'Оператор'), ('manager', 'Руководитель'), ('admin', 'Администратор')], default='operator', max_length=20, verbose_name='Роль'),
        ),
    ]
