# Generated by Django 5.1.3 on 2026-07-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0006_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleinspection',
            name='front_photo_taken_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата фото спереди'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='left_photo_taken_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата фото слева'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='mileage_photo_taken_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата фото пробега'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='rear_photo_taken_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата фото сзади'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='right_photo_taken_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата фото справа'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='vin_photo_taken_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата фото VIN'),
        ),
    ]
