# Generated by Django 5.1.3 on 2026-07-28 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0011_vehicleinspection_vehicle_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleinspection',
            name='vehicle_category',
            field=models.CharField(choices=[('M1', 'M1'), ('M2', 'M2'), ('M3', 'M3'), ('N1', 'N1'), ('N2', 'N2'), ('N3', 'N3')], default='M1', max_length=2, verbose_name='Категория авто'),
        ),
    ]
