# Generated by Django 5.1.3 on 2026-07-28 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0012_alter_vehicleinspection_vehicle_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyInspectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(verbose_name='Дата отчета')),
                ('rows', models.JSONField(blank=True, default=list, verbose_name='Строки отчета')),
                ('total_count', models.PositiveIntegerField(default=0, verbose_name='Всего')),
                ('category_counts', models.JSONField(blank=True, default=dict, verbose_name='Итоги по категориям')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_reports', to='inspections.branch', verbose_name='Филиал')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_inspection_reports', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Дневной отчет осмотров',
                'verbose_name_plural': 'Дневные отчеты осмотров',
                'ordering': ['-report_date', 'branch__name'],
                'constraints': [models.UniqueConstraint(fields=('report_date', 'branch'), name='unique_daily_inspection_report_per_branch')],
            },
        ),
    ]
