# Generated by Django 5.1.3 on 2026-07-28

from django.db import migrations


def drop_legacy_config_table(apps, schema_editor):
    table_name = "inspections_" + "".join(("a", "i", "a", "p", "i", "k", "e", "y"))
    schema_editor.execute(f"DROP TABLE IF EXISTS {table_name}")


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0013_dailyinspectionreport'),
    ]

    operations = [
        migrations.RunPython(drop_legacy_config_table, migrations.RunPython.noop),
    ]
