# Generated by Django 5.1.3 on 2026-07-30 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0014_drop_legacy_config_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleinspection',
            name='operation_type',
            field=models.CharField(choices=[('tech_inspection', 'Техосмотр'), ('sbgts', 'СБГТС'), ('legalization', 'Легализация'), ('conversion', 'Переоборудование')], default='sbgts', max_length=32, verbose_name='Категория операции'),
        ),
    ]
