# Generated by Django 5.1.3 on 2026-07-30 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0015_vehicleinspection_operation_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleInspectionExtraPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='inspections/conversion/', verbose_name='Фото переоборудованной части')),
                ('taken_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_photos', to='inspections.vehicleinspection', verbose_name='Осмотр')),
            ],
            options={
                'verbose_name': 'Дополнительное фото',
                'verbose_name_plural': 'Дополнительные фото',
                'ordering': ['id'],
            },
        ),
    ]
