# Generated by Django 5.1.3 on 2026-08-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0016_vehicleinspectionextraphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleinspection',
            name='vin',
            field=models.CharField(max_length=17, verbose_name='VIN номер'),
        ),
    ]
