# Generated by Django 5.1.3 on 2026-08-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0017_alter_vehicleinspection_vin'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleinspection',
            name='application_photo',
            field=models.ImageField(blank=True, null=True, upload_to='inspections/application/', verbose_name='Фото заявки'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='application_photo_taken_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата фото заявки'),
        ),
    ]
