# Generated by Django 5.1.3 on 2026-08-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0018_vehicleinspection_application_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAIApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Основной ключ', max_length=120, verbose_name='Название')),
                ('api_key', models.CharField(max_length=255, verbose_name='API key')),
                ('model', models.CharField(default='gpt-5.6-terra', max_length=80, verbose_name='Модель')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'OpenAI API key',
                'verbose_name_plural': 'OpenAI API keys',
            },
        ),
    ]
