# Generated by Django 5.1.3 on 2026-08-03 09:51

from django.db import migrations, models


def upgrade_default_model(apps, schema_editor):
    OpenAIApiKey = apps.get_model("inspections", "OpenAIApiKey")
    OpenAIApiKey.objects.filter(model__in=["gpt-4o-mini", "gpt-4.1"]).update(model="gpt-5.6-terra")


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0019_openaiapikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openaiapikey',
            name='model',
            field=models.CharField(default='gpt-5.6-terra', max_length=80, verbose_name='Модель'),
        ),
        migrations.RunPython(upgrade_default_model, migrations.RunPython.noop),
    ]
