# Generated by Django 5.1.3 on 2026-08-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0020_alter_openaiapikey_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleinspection',
            name='application_pdf',
            field=models.FileField(blank=True, null=True, upload_to='inspections/applications/', verbose_name='PDF заявки клиента'),
        ),
    ]
