# Generated by Django 5.1.3 on 2026-08-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0022_userprofile_phone_number_loginchallenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginchallenge',
            name='wazzup_chat_id',
            field=models.CharField(blank=True, max_length=32, verbose_name='Wazzup chatId'),
        ),
        migrations.AddField(
            model_name='loginchallenge',
            name='wazzup_message_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='Wazzup messageId'),
        ),
        migrations.AddField(
            model_name='loginchallenge',
            name='wazzup_response',
            field=models.JSONField(blank=True, null=True, verbose_name='Ответ Wazzup'),
        ),
    ]
