# Generated by Django 5.1.3 on 2026-08-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0023_loginchallenge_wazzup_chat_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_use_app',
            field=models.BooleanField(default=True, help_text='Если выключено, пользователь не сможет войти в web/mobile API.', verbose_name='Доступ к APK'),
        ),
    ]
