# Generated by Django 5.1.3 on 2026-08-18 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0024_userprofile_can_use_app'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyInspectionReport',
        ),
    ]
