# Generated by Django 5.1.3 on 2026-08-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0025_delete_dailyinspectionreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleinspection',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Сумма'),
        ),
        migrations.CreateModel(
            name='InspectionPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('tech_inspection', 'Техосмотр'), ('sbgts', 'СБКТС'), ('legalization', 'Легализация'), ('conversion', 'Переоборудование')], max_length=32, verbose_name='Тип операции')),
                ('vehicle_category', models.CharField(blank=True, choices=[('M1', 'M1'), ('M2', 'M2'), ('M3', 'M3'), ('N1', 'N1'), ('N2', 'N2'), ('N3', 'N3')], help_text='Заполняется для СБКТС и техосмотра. Для остальных операций оставить пустым.', max_length=2, verbose_name='Категория авто')),
                ('amount', models.PositiveIntegerField(verbose_name='Сумма')),
                ('effective_from', models.DateField(verbose_name='Действует с')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Цена осмотра',
                'verbose_name_plural': 'Цены осмотров',
                'ordering': ['operation_type', 'vehicle_category', '-effective_from'],
                'constraints': [models.UniqueConstraint(fields=('operation_type', 'vehicle_category', 'effective_from'), name='unique_inspection_price_period')],
            },
        ),
    ]
