# Generated by Django 5.1.3 on 2026-08-20 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0031_apiratelimit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=32, verbose_name='VIN')),
                ('applicant', models.CharField(blank=True, max_length=200, verbose_name='ФИО')),
                ('inn', models.CharField(blank=True, max_length=14, verbose_name='ИНН')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('vehicle_name', models.CharField(blank=True, max_length=200, verbose_name='Марка авто')),
                ('plate_number', models.CharField(blank=True, max_length=20, verbose_name='Гос. номер')),
                ('year', models.CharField(blank=True, max_length=4, verbose_name='Год выпуска')),
                ('application_pdf', models.FileField(blank=True, max_length=255, null=True, upload_to='applications/pdfs/', verbose_name='PDF заявки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_applications', to='inspections.vehicleinspection', verbose_name='Осмотр')),
            ],
            options={
                'verbose_name': 'Заявка клиента',
                'verbose_name_plural': 'Заявки клиентов',
                'ordering': ['-created_at'],
            },
        ),
    ]
