# Generated by Django 6.0.8 on 2026-08-20 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0031_apiratelimit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(blank=True, max_length=200, verbose_name='ФИО заявителя')),
                ('inn', models.CharField(blank=True, max_length=20, verbose_name='ИНН')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('vin', models.CharField(max_length=32, verbose_name='VIN / номер кузова')),
                ('pdf', models.FileField(max_length=255, upload_to='inspections/applications/', verbose_name='PDF заявки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_applications', to='inspections.vehicleinspection', verbose_name='Осмотр')),
            ],
            options={
                'verbose_name': 'Заявка клиента',
                'verbose_name_plural': 'Заявки клиентов',
                'ordering': ['-created_at'],
            },
        ),
    ]
