# Generated by Django 6.0.8 on 2026-08-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0032_clientapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientapplication',
            name='plate_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Гос номер'),
        ),
        migrations.AddField(
            model_name='clientapplication',
            name='vehicle_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Марка / модель авто'),
        ),
        migrations.AddField(
            model_name='clientapplication',
            name='year',
            field=models.CharField(blank=True, max_length=10, verbose_name='Год выпуска'),
        ),
    ]
