# Generated by Django 6.0.8 on 2026-08-21 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0034_clientapplication_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('operator', 'Оператор'), ('mvd', 'МВД'), ('manager', 'Руководитель'), ('admin', 'Администратор')], default='operator', max_length=20, verbose_name='Роль'),
        ),
    ]
