part of 'main.dart';

const _vehicleCatalog = <String, List<String>>{
  'Toyota': [
    'Corolla',
    'Camry',
    'RAV4',
    'Land Cruiser',
    'Land Cruiser Prado',
    'Highlander',
    'Hilux',
    'Fortuner',
    'C-HR',
    'Yaris',
    'Crown',
    'Prius',
    'Alphard',
    'Hiace',
    'Noah',
    'Voxy',
    'Estima',
    'Mark X',
    'Avalon',
    'Venza',
    'Tundra',
    'Sequoia',
    'Tacoma',
    '4Runner',
    'Sienna',
    'Supra',
    'GT86',
    'Corolla Cross',
    'Grand Hiace',
    'Probox',
    'Ractis',
    'Passo',
  ],
  'Lexus': [
    'RX',
    'ES',
    'NX',
    'LX',
    'GX',
    'GS',
    'LS',
    'IS',
    'UX',
    'CT',
    'LM',
    'TX',
    'RC',
    'LC',
  ],
  'Hyundai': [
    'Sonata',
    'Elantra',
    'Accent',
    'Tucson',
    'Santa Fe',
    'Creta',
    'Solaris',
    'Palisade',
    'Kona',
    'Grandeur',
    'Starex',
    'Porter',
    'H1',
    'Getz',
    'Matrix',
    'ix35',
    'Avante',
    'Trajet',
    'Ioniq',
  ],
  'Kia': [
    'K5',
    'K3',
    'Rio',
    'Sportage',
    'Sorento',
    'Cerato',
    'Mohave',
    'Soul',
    'Seltos',
    'Telluride',
    'Optima',
    'Carnival',
    'Picanto',
    'Ceed',
    'Stinger',
    'EV6',
    'Morning',
    'Spectra',
    'Bongo',
    'Ray',
  ],
  'Mercedes-Benz': [
    'C-Class',
    'E-Class',
    'S-Class',
    'GLC',
    'GLE',
    'G-Class',
    'GLS',
    'A-Class',
    'CLA',
    'CLS',
    'GLB',
    'Vito',
    'Sprinter',
    'ML',
    'GLK',
    'V-Class',
    'AMG GT',
  ],
  'BMW': [
    '3 Series',
    '5 Series',
    '7 Series',
    'X3',
    'X5',
    'X7',
    'X1',
    'X4',
    'X6',
    '1 Series',
    '2 Series',
    'M3',
    'M5',
    'iX',
    'Z4',
    '4 Series',
    'X3 M',
    'XM',
  ],
  'Audi': [
    'A3',
    'A4',
    'A6',
    'A8',
    'Q3',
    'Q5',
    'Q7',
    'Q8',
    'TT',
    'Q2',
    'RS6',
    'A5',
    'A7',
    'S3',
    'SQ5',
    'e-tron',
    'A4 B5',
    '80',
    '100',
  ],
  'Volkswagen': [
    'Golf',
    'Passat',
    'Tiguan',
    'Polo',
    'Jetta',
    'Touareg',
    'Amarok',
    'Beetle',
    'Crafter',
    'Multivan',
    'Caddy',
    'Bora',
    'Vento',
    'Passat CC',
    'Arteon',
    'ID.4',
    'Transporter',
  ],
  'Honda': [
    'Civic',
    'Accord',
    'CR-V',
    'Pilot',
    'Fit',
    'HR-V',
    'Odyssey',
    'Stepwagon',
    'Stream',
    'Vezel',
    'City',
    'Jazz',
    'CR-Z',
    'Civic Type R',
  ],
  'Nissan': [
    'Almera',
    'Altima',
    'X-Trail',
    'Patrol',
    'Qashqai',
    'Teana',
    'Sunny',
    'Skyline',
    'GT-R',
    'Murano',
    'Navara',
    'Pathfinder',
    'Serena',
    'Juke',
    'Sentra',
    'Tiida',
    'Micra',
    'Note',
  ],
  'Mitsubishi': [
    'Lancer',
    'Outlander',
    'Pajero',
    'ASX',
    'Eclipse Cross',
    'L200',
    'Delica',
    'Galant',
    'Montero',
    'RVR',
    'Mirage',
  ],
  'Chevrolet': [
    'Cruze',
    'Malibu',
    'Trailblazer',
    'Captiva',
    'Tahoe',
    'Suburban',
    'Camaro',
    'Silverado',
    'Aveo',
    'Cobalt',
    'Spark',
    'Blazer',
    'Lacetti',
    'Epica',
    'Orlando',
  ],
  'Subaru': [
    'Outback',
    'Forester',
    'Legacy',
    'Impreza',
    'WRX',
    'XV',
    'Ascent',
    'Crosstrek',
    'Levorg',
    'BRZ',
    'Tribeca',
  ],
  'Mazda': [
    '3',
    '6',
    'CX-5',
    'CX-9',
    'CX-30',
    'MX-5',
    'RX-7',
    'RX-8',
    'BT-50',
    'CX-3',
    'Familia',
    'Premacy',
  ],
  'Skoda': [
    'Octavia',
    'Rapid',
    'Kodiaq',
    'Karoq',
    'Fabia',
    'Superb',
    'Scala',
    'Yeti',
    'Kamiq',
    'Enyaq',
  ],
  'Ford': [
    'Focus',
    'Fiesta',
    'Mondeo',
    'Escape',
    'Explorer',
    'Ranger',
    'Mustang',
    'Everest',
    'Kuga',
    'F-150',
    'Transit',
    'Fusion',
    'Galaxy',
  ],
  'Opel': [
    'Astra',
    'Corsa',
    'Insignia',
    'Mokka',
    'Zafira',
    'Vectra',
    'Meriva',
    'Antara',
    'Grandland',
    'Crossland',
    'Vivaro',
  ],
  'Renault': [
    'Duster',
    'Logan',
    'Sandero',
    'Arkana',
    'Kaptur',
    'Megane',
    'Clio',
    'Koleos',
    'Scenic',
    'Fluence',
    'Symbol',
    'Kadjar',
  ],
  'Peugeot': [
    '208',
    '308',
    '3008',
    '5008',
    '408',
    '2008',
    '508',
    'Partner',
    'Boxer',
    '307',
  ],
  'Citroën': [
    'C3',
    'C4',
    'C5',
    'C-Elysee',
    'C3 Aircross',
    'Berlingo',
    'Jumper',
    'Grand C4',
  ],
  'Suzuki': [
    'Vitara',
    'Swift',
    'Jimny',
    'SX4',
    'Grand Vitara',
    'Baleno',
    'Escudo',
    'Ignis',
    'Wagon R',
  ],
  'Jeep': [
    'Grand Cherokee',
    'Cherokee',
    'Wrangler',
    'Compass',
    'Renegade',
    'Gladiator',
    'Liberty',
  ],
  'Land Rover': [
    'Range Rover',
    'Range Rover Sport',
    'Discovery',
    'Defender',
    'Evoque',
    'Velar',
    'Freelander',
  ],
  'Volvo': [
    'XC60',
    'XC90',
    'S60',
    'S90',
    'V60',
    'XC40',
    'V90',
    'S80',
    'V70',
    'XC70',
  ],
  'Porsche': [
    '911',
    'Cayenne',
    'Macan',
    'Panamera',
    'Taycan',
    'Boxster',
    'Cayman',
  ],
  'Infiniti': ['QX50', 'QX60', 'QX80', 'Q50', 'Q60', 'FX35', 'EX35', 'QX70'],
  'Acura': ['MDX', 'RDX', 'TLX', 'ILX', 'NSX', 'RLX'],
  'Cadillac': ['Escalade', 'CTS', 'XT5', 'XT4', 'SRX', 'XTS', 'CT5'],
  'Daewoo': [
    'Matiz',
    'Nexia',
    'Lacetti',
    'Gentra',
    'Damas',
    'Espero',
    'Leganza',
    'Nubira',
    'Kalos',
  ],
  'Lada': [
    'Vesta',
    'Granta',
    'Largus',
    'Niva',
    'Kalina',
    'Priora',
    'XRAY',
    '4x4',
    'Samara',
  ],
  'GAZ': ['3110', '31105', '3302', 'Gazelle', 'Sobol', '3102'],
  'UAZ': ['Patriot', 'Hunter', '469', '452', '2206', '31512', 'Pickup'],
  'BYD': [
    'Song',
    'Han',
    'Tang',
    'Seagull',
    'Dolphin',
    'Qin',
    'Atto 3',
    'Seal',
    'Yuan',
  ],
  'Chery': [
    'Tiggo 4',
    'Tiggo 7',
    'Tiggo 8',
    'Tiggo 9',
    'Arrizo',
    'QQ',
    'Tiggo 5',
    'Cowin',
  ],
  'Geely': [
    'Atlas',
    'Emgrand',
    'Coolray',
    'Monjaro',
    'Tugella',
    'X7',
    'Okavango',
    'Boyue',
    'GC6',
  ],
  'Haval': ['H9', 'F7', 'H6', 'Jolion', 'Dargo', 'H2', 'H5', 'M6', 'Cool Dog'],
  'Great Wall': ['Hover', 'Wingle', 'Poer', 'Cowry', 'C30', 'C50'],
  'Dongfeng': ['580', 'SX6', 'Glory', 'Fengon', 'H30', 'AX7'],
  'JAC': ['J7', 'S3', 'S4', 'T8', 'X8', 'Refine', 'K5'],
  'BAIC': ['X5', 'X7', 'U5', 'U7', 'BJ40'],
  'Changan': ['CS35', 'CS55', 'CS75', 'Uni-T', 'Uni-K', 'Eado', 'Alsvin'],
  'Lifan': ['X50', 'X60', 'Solano', '620', 'Cebria'],
  'Tesla': ['Model 3', 'Model S', 'Model X', 'Model Y', 'Cybertruck'],
  'Mini': ['Cooper', 'Countryman', 'Clubman', 'Paceman'],
  'Fiat': ['500', 'Panda', 'Tipo', 'Ducato', 'Doblo'],
  'Seat': ['Leon', 'Ibiza', 'Ateca', 'Arona', 'Toledo'],
  'Alfa Romeo': ['Giulia', 'Stelvio', '159', 'Giulietta'],
  'Datsun': ['ON-DO', 'MI-DO', 'GO'],
  'Isuzu': ['D-Max', 'Trooper', 'Elf', 'Bighorn', 'NPR'],
  'MAN': ['TGS', 'TGA', 'TGL', 'TGX'],
  'Scania': ['R', 'P', 'G', 'S'],
  'Volga': ['3110', '31105', '3102', '24', '21'],
  'Bentley': ['Continental GT', 'Bentayga', 'Flying Spur', 'Mulsanne'],
  'Rolls-Royce': ['Phantom', 'Ghost', 'Cullinan', 'Wraith', 'Dawn'],
  'Lamborghini': ['Urus', 'Huracan', 'Aventador'],
  'Ferrari': ['488', '812', 'F8', 'Roma', 'Purosangue'],
  'Maserati': ['Levante', 'Ghibli', 'Quattroporte', 'MC20'],
  'McLaren': ['720S', 'GT', 'Artura', '750S'],
  'Aston Martin': ['DB11', 'DBS', 'DBX', 'Vantage'],
  'Iveco': ['Daily', 'Eurocargo', 'Trakker'],
  'Kamaz': ['43118', '6520', '5490'],
  'Tatra': ['T815', 'T163', 'Phoenix'],
  'ZAZ': ['Lanos', 'Sens', 'Chance', 'Forza'],
  'Moskvich': ['412', '2140', '408', '407', '3'],
  'Dacia': ['Logan', 'Duster', 'Sandero', 'Lodgy', 'Spring'],
  'Buick': ['Encore', 'Enclave', 'Envision', 'LaCrosse'],
  'GMC': ['Yukon', 'Sierra', 'Acadia', 'Terrain'],
  'Hummer': ['H1', 'H2', 'H3'],
  'Lincoln': ['Navigator', 'MKX', 'Continental', 'Aviator'],
  'Pontiac': ['Grand Prix', 'Grand Am', 'Firebird'],
  'Saab': ['9-3', '9-5', '900'],
  'Smart': ['Fortwo', 'Forfour'],
  'SsangYong': [
    'Actyon',
    'Kyron',
    'Rexton',
    'Tivoli',
    'Korando',
    'Musso',
    'Rodius',
  ],
};

List<String> _catalogBrands() {
  return _vehicleCatalog.keys.toList()..sort();
}

List<String> _catalogModels(String brand) {
  return _vehicleCatalog[brand] ?? const <String>[];
}
